/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedBehaviorRouteImport } from './routes/_authenticated/behavior'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFaceIdRouteImport } from './routes/_authenticated/face-id'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedGradesRouteImport } from './routes/_authenticated/grades'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedTeacherBalanceRouteImport } from './routes/_authenticated/teacher-balance'
import { Route as AuthenticatedTeacherPanelRouteImport } from './routes/_authenticated/teacher-panel'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsCashRegisterRouteImport } from './routes/_authenticated/settings.cash-register'
import { Route as AuthenticatedSettingsContactRouteImport } from './routes/_authenticated/settings.contact'
import { Route as AuthenticatedSettingsCredentialsRouteImport } from './routes/_authenticated/settings.credentials'
import { Route as AuthenticatedSettingsDesignRouteImport } from './routes/_authenticated/settings.design'
import { Route as AuthenticatedSettingsDirectorReportRouteImport } from './routes/_authenticated/settings.director-report'
import { Route as AuthenticatedSettingsGradeTemplateRouteImport } from './routes/_authenticated/settings.grade-template'
import { Route as AuthenticatedSettingsHomepageCoursesRouteImport } from './routes/_authenticated/settings.homepage-courses'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsMarketplaceRouteImport } from './routes/_authenticated/settings.marketplace'
import { Route as AuthenticatedSettingsNewsRouteImport } from './routes/_authenticated/settings.news'
import { Route as AuthenticatedSettingsReportsRouteImport } from './routes/_authenticated/settings.reports'
import { Route as AuthenticatedSettingsStatsRouteImport } from './routes/_authenticated/settings.stats'
import { Route as AuthenticatedSettingsSubjectsRouteImport } from './routes/_authenticated/settings.subjects'
import { Route as AuthenticatedSettingsTeachersRouteImport } from './routes/_authenticated/settings.teachers'
import { Route as AuthenticatedSettingsTelephonyRouteImport } from './routes/_authenticated/settings.telephony'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as ApiPublicCronDailyReportRouteImport } from './routes/api/public/cron.daily-report'
import { Route as ApiPublicCronNotificationsDispatchRouteImport } from './routes/api/public/cron.notifications-dispatch'
import { Route as ApiPublicCronParentDigestRouteImport } from './routes/api/public/cron.parent-digest'
import { Route as ApiPublicCronReceiptQueueRouteImport } from './routes/api/public/cron.receipt-queue'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron.reminders'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram.webhook'
import { Route as ApiPublicTelephonyOutboxRouteImport } from './routes/api/public/telephony.outbox'
import { Route as ApiPublicTelephonySipWebhookRouteImport } from './routes/api/public/telephony.sip-webhook'
import { Route as ApiPublicTelephonyWebhookRouteImport } from './routes/api/public/telephony.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBehaviorRoute = AuthenticatedBehaviorRouteImport.update({
  id: '/behavior',
  path: '/behavior',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaceIdRoute = AuthenticatedFaceIdRouteImport.update({
  id: '/face-id',
  path: '/face-id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradesRoute = AuthenticatedGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherBalanceRoute =
  AuthenticatedTeacherBalanceRouteImport.update({
    id: '/teacher-balance',
    path: '/teacher-balance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherPanelRoute =
  AuthenticatedTeacherPanelRouteImport.update({
    id: '/teacher-panel',
    path: '/teacher-panel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCashRegisterRoute =
  AuthenticatedSettingsCashRegisterRouteImport.update({
    id: '/cash-register',
    path: '/cash-register',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsContactRoute =
  AuthenticatedSettingsContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCredentialsRoute =
  AuthenticatedSettingsCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDesignRoute =
  AuthenticatedSettingsDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDirectorReportRoute =
  AuthenticatedSettingsDirectorReportRouteImport.update({
    id: '/director-report',
    path: '/director-report',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGradeTemplateRoute =
  AuthenticatedSettingsGradeTemplateRouteImport.update({
    id: '/grade-template',
    path: '/grade-template',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsHomepageCoursesRoute =
  AuthenticatedSettingsHomepageCoursesRouteImport.update({
    id: '/homepage-courses',
    path: '/homepage-courses',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMarketplaceRoute =
  AuthenticatedSettingsMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNewsRoute =
  AuthenticatedSettingsNewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsReportsRoute =
  AuthenticatedSettingsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsStatsRoute =
  AuthenticatedSettingsStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSubjectsRoute =
  AuthenticatedSettingsSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeachersRoute =
  AuthenticatedSettingsTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTelephonyRoute =
  AuthenticatedSettingsTelephonyRouteImport.update({
    id: '/telephony',
    path: '/telephony',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)
const ApiPublicCronDailyReportRoute =
  ApiPublicCronDailyReportRouteImport.update({
    id: '/api/public/cron/daily-report',
    path: '/api/public/cron/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronNotificationsDispatchRoute =
  ApiPublicCronNotificationsDispatchRouteImport.update({
    id: '/api/public/cron/notifications-dispatch',
    path: '/api/public/cron/notifications-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronParentDigestRoute =
  ApiPublicCronParentDigestRouteImport.update({
    id: '/api/public/cron/parent-digest',
    path: '/api/public/cron/parent-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReceiptQueueRoute =
  ApiPublicCronReceiptQueueRouteImport.update({
    id: '/api/public/cron/receipt-queue',
    path: '/api/public/cron/receipt-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron/reminders',
  path: '/api/public/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelephonyOutboxRoute =
  ApiPublicTelephonyOutboxRouteImport.update({
    id: '/api/public/telephony/outbox',
    path: '/api/public/telephony/outbox',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelephonySipWebhookRoute =
  ApiPublicTelephonySipWebhookRouteImport.update({
    id: '/api/public/telephony/sip-webhook',
    path: '/api/public/telephony/sip-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelephonyWebhookRoute =
  ApiPublicTelephonyWebhookRouteImport.update({
    id: '/api/public/telephony/webhook',
    path: '/api/public/telephony/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/behavior': typeof AuthenticatedBehaviorRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/face-id': typeof AuthenticatedFaceIdRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/grades': typeof AuthenticatedGradesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/import': typeof AuthenticatedImportRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/teacher-balance': typeof AuthenticatedTeacherBalanceRoute
  '/teacher-panel': typeof AuthenticatedTeacherPanelRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/settings/cash-register': typeof AuthenticatedSettingsCashRegisterRoute
  '/settings/contact': typeof AuthenticatedSettingsContactRoute
  '/settings/credentials': typeof AuthenticatedSettingsCredentialsRoute
  '/settings/design': typeof AuthenticatedSettingsDesignRoute
  '/settings/director-report': typeof AuthenticatedSettingsDirectorReportRoute
  '/settings/grade-template': typeof AuthenticatedSettingsGradeTemplateRoute
  '/settings/homepage-courses': typeof AuthenticatedSettingsHomepageCoursesRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/marketplace': typeof AuthenticatedSettingsMarketplaceRoute
  '/settings/news': typeof AuthenticatedSettingsNewsRoute
  '/settings/reports': typeof AuthenticatedSettingsReportsRoute
  '/settings/stats': typeof AuthenticatedSettingsStatsRoute
  '/settings/subjects': typeof AuthenticatedSettingsSubjectsRoute
  '/settings/teachers': typeof AuthenticatedSettingsTeachersRoute
  '/settings/telephony': typeof AuthenticatedSettingsTelephonyRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
  '/api/public/cron/notifications-dispatch': typeof ApiPublicCronNotificationsDispatchRoute
  '/api/public/cron/parent-digest': typeof ApiPublicCronParentDigestRoute
  '/api/public/cron/receipt-queue': typeof ApiPublicCronReceiptQueueRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telephony/outbox': typeof ApiPublicTelephonyOutboxRoute
  '/api/public/telephony/sip-webhook': typeof ApiPublicTelephonySipWebhookRoute
  '/api/public/telephony/webhook': typeof ApiPublicTelephonyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/behavior': typeof AuthenticatedBehaviorRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/face-id': typeof AuthenticatedFaceIdRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/grades': typeof AuthenticatedGradesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/import': typeof AuthenticatedImportRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/search': typeof AuthenticatedSearchRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/teacher-balance': typeof AuthenticatedTeacherBalanceRoute
  '/teacher-panel': typeof AuthenticatedTeacherPanelRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/settings/cash-register': typeof AuthenticatedSettingsCashRegisterRoute
  '/settings/contact': typeof AuthenticatedSettingsContactRoute
  '/settings/credentials': typeof AuthenticatedSettingsCredentialsRoute
  '/settings/design': typeof AuthenticatedSettingsDesignRoute
  '/settings/director-report': typeof AuthenticatedSettingsDirectorReportRoute
  '/settings/grade-template': typeof AuthenticatedSettingsGradeTemplateRoute
  '/settings/homepage-courses': typeof AuthenticatedSettingsHomepageCoursesRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/marketplace': typeof AuthenticatedSettingsMarketplaceRoute
  '/settings/news': typeof AuthenticatedSettingsNewsRoute
  '/settings/reports': typeof AuthenticatedSettingsReportsRoute
  '/settings/stats': typeof AuthenticatedSettingsStatsRoute
  '/settings/subjects': typeof AuthenticatedSettingsSubjectsRoute
  '/settings/teachers': typeof AuthenticatedSettingsTeachersRoute
  '/settings/telephony': typeof AuthenticatedSettingsTelephonyRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
  '/api/public/cron/notifications-dispatch': typeof ApiPublicCronNotificationsDispatchRoute
  '/api/public/cron/parent-digest': typeof ApiPublicCronParentDigestRoute
  '/api/public/cron/receipt-queue': typeof ApiPublicCronReceiptQueueRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telephony/outbox': typeof ApiPublicTelephonyOutboxRoute
  '/api/public/telephony/sip-webhook': typeof ApiPublicTelephonySipWebhookRoute
  '/api/public/telephony/webhook': typeof ApiPublicTelephonyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/behavior': typeof AuthenticatedBehaviorRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/face-id': typeof AuthenticatedFaceIdRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/grades': typeof AuthenticatedGradesRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/teacher-balance': typeof AuthenticatedTeacherBalanceRoute
  '/_authenticated/teacher-panel': typeof AuthenticatedTeacherPanelRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/_authenticated/settings/cash-register': typeof AuthenticatedSettingsCashRegisterRoute
  '/_authenticated/settings/contact': typeof AuthenticatedSettingsContactRoute
  '/_authenticated/settings/credentials': typeof AuthenticatedSettingsCredentialsRoute
  '/_authenticated/settings/design': typeof AuthenticatedSettingsDesignRoute
  '/_authenticated/settings/director-report': typeof AuthenticatedSettingsDirectorReportRoute
  '/_authenticated/settings/grade-template': typeof AuthenticatedSettingsGradeTemplateRoute
  '/_authenticated/settings/homepage-courses': typeof AuthenticatedSettingsHomepageCoursesRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/marketplace': typeof AuthenticatedSettingsMarketplaceRoute
  '/_authenticated/settings/news': typeof AuthenticatedSettingsNewsRoute
  '/_authenticated/settings/reports': typeof AuthenticatedSettingsReportsRoute
  '/_authenticated/settings/stats': typeof AuthenticatedSettingsStatsRoute
  '/_authenticated/settings/subjects': typeof AuthenticatedSettingsSubjectsRoute
  '/_authenticated/settings/teachers': typeof AuthenticatedSettingsTeachersRoute
  '/_authenticated/settings/telephony': typeof AuthenticatedSettingsTelephonyRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
  '/api/public/cron/notifications-dispatch': typeof ApiPublicCronNotificationsDispatchRoute
  '/api/public/cron/parent-digest': typeof ApiPublicCronParentDigestRoute
  '/api/public/cron/receipt-queue': typeof ApiPublicCronReceiptQueueRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telephony/outbox': typeof ApiPublicTelephonyOutboxRoute
  '/api/public/telephony/sip-webhook': typeof ApiPublicTelephonySipWebhookRoute
  '/api/public/telephony/webhook': typeof ApiPublicTelephonyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bootstrap'
    | '/attendance'
    | '/behavior'
    | '/calls'
    | '/dashboard'
    | '/face-id'
    | '/finance'
    | '/grades'
    | '/groups'
    | '/import'
    | '/leads'
    | '/marketplace'
    | '/messages'
    | '/payments'
    | '/reports'
    | '/rooms'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/students'
    | '/teacher-balance'
    | '/teacher-panel'
    | '/receipt/$id'
    | '/settings/cash-register'
    | '/settings/contact'
    | '/settings/credentials'
    | '/settings/design'
    | '/settings/director-report'
    | '/settings/grade-template'
    | '/settings/homepage-courses'
    | '/settings/integrations'
    | '/settings/marketplace'
    | '/settings/news'
    | '/settings/reports'
    | '/settings/stats'
    | '/settings/subjects'
    | '/settings/teachers'
    | '/settings/telephony'
    | '/students/$id'
    | '/settings/'
    | '/api/public/cron/daily-report'
    | '/api/public/cron/notifications-dispatch'
    | '/api/public/cron/parent-digest'
    | '/api/public/cron/receipt-queue'
    | '/api/public/cron/reminders'
    | '/api/public/telegram/webhook'
    | '/api/public/telephony/outbox'
    | '/api/public/telephony/sip-webhook'
    | '/api/public/telephony/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bootstrap'
    | '/attendance'
    | '/behavior'
    | '/calls'
    | '/dashboard'
    | '/face-id'
    | '/finance'
    | '/grades'
    | '/groups'
    | '/import'
    | '/leads'
    | '/marketplace'
    | '/messages'
    | '/payments'
    | '/reports'
    | '/rooms'
    | '/schedule'
    | '/search'
    | '/students'
    | '/teacher-balance'
    | '/teacher-panel'
    | '/receipt/$id'
    | '/settings/cash-register'
    | '/settings/contact'
    | '/settings/credentials'
    | '/settings/design'
    | '/settings/director-report'
    | '/settings/grade-template'
    | '/settings/homepage-courses'
    | '/settings/integrations'
    | '/settings/marketplace'
    | '/settings/news'
    | '/settings/reports'
    | '/settings/stats'
    | '/settings/subjects'
    | '/settings/teachers'
    | '/settings/telephony'
    | '/students/$id'
    | '/settings'
    | '/api/public/cron/daily-report'
    | '/api/public/cron/notifications-dispatch'
    | '/api/public/cron/parent-digest'
    | '/api/public/cron/receipt-queue'
    | '/api/public/cron/reminders'
    | '/api/public/telegram/webhook'
    | '/api/public/telephony/outbox'
    | '/api/public/telephony/sip-webhook'
    | '/api/public/telephony/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bootstrap'
    | '/_authenticated/attendance'
    | '/_authenticated/behavior'
    | '/_authenticated/calls'
    | '/_authenticated/dashboard'
    | '/_authenticated/face-id'
    | '/_authenticated/finance'
    | '/_authenticated/grades'
    | '/_authenticated/groups'
    | '/_authenticated/import'
    | '/_authenticated/leads'
    | '/_authenticated/marketplace'
    | '/_authenticated/messages'
    | '/_authenticated/payments'
    | '/_authenticated/reports'
    | '/_authenticated/rooms'
    | '/_authenticated/schedule'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/teacher-balance'
    | '/_authenticated/teacher-panel'
    | '/receipt/$id'
    | '/_authenticated/settings/cash-register'
    | '/_authenticated/settings/contact'
    | '/_authenticated/settings/credentials'
    | '/_authenticated/settings/design'
    | '/_authenticated/settings/director-report'
    | '/_authenticated/settings/grade-template'
    | '/_authenticated/settings/homepage-courses'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/marketplace'
    | '/_authenticated/settings/news'
    | '/_authenticated/settings/reports'
    | '/_authenticated/settings/stats'
    | '/_authenticated/settings/subjects'
    | '/_authenticated/settings/teachers'
    | '/_authenticated/settings/telephony'
    | '/_authenticated/students/$id'
    | '/_authenticated/settings/'
    | '/api/public/cron/daily-report'
    | '/api/public/cron/notifications-dispatch'
    | '/api/public/cron/parent-digest'
    | '/api/public/cron/receipt-queue'
    | '/api/public/cron/reminders'
    | '/api/public/telegram/webhook'
    | '/api/public/telephony/outbox'
    | '/api/public/telephony/sip-webhook'
    | '/api/public/telephony/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BootstrapRoute: typeof BootstrapRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
  ApiPublicCronDailyReportRoute: typeof ApiPublicCronDailyReportRoute
  ApiPublicCronNotificationsDispatchRoute: typeof ApiPublicCronNotificationsDispatchRoute
  ApiPublicCronParentDigestRoute: typeof ApiPublicCronParentDigestRoute
  ApiPublicCronReceiptQueueRoute: typeof ApiPublicCronReceiptQueueRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicTelephonyOutboxRoute: typeof ApiPublicTelephonyOutboxRoute
  ApiPublicTelephonySipWebhookRoute: typeof ApiPublicTelephonySipWebhookRoute
  ApiPublicTelephonyWebhookRoute: typeof ApiPublicTelephonyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/behavior': {
      id: '/_authenticated/behavior'
      path: '/behavior'
      fullPath: '/behavior'
      preLoaderRoute: typeof AuthenticatedBehaviorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/face-id': {
      id: '/_authenticated/face-id'
      path: '/face-id'
      fullPath: '/face-id'
      preLoaderRoute: typeof AuthenticatedFaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grades': {
      id: '/_authenticated/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthenticatedGradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-balance': {
      id: '/_authenticated/teacher-balance'
      path: '/teacher-balance'
      fullPath: '/teacher-balance'
      preLoaderRoute: typeof AuthenticatedTeacherBalanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-panel': {
      id: '/_authenticated/teacher-panel'
      path: '/teacher-panel'
      fullPath: '/teacher-panel'
      preLoaderRoute: typeof AuthenticatedTeacherPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/cash-register': {
      id: '/_authenticated/settings/cash-register'
      path: '/cash-register'
      fullPath: '/settings/cash-register'
      preLoaderRoute: typeof AuthenticatedSettingsCashRegisterRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/contact': {
      id: '/_authenticated/settings/contact'
      path: '/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof AuthenticatedSettingsContactRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/credentials': {
      id: '/_authenticated/settings/credentials'
      path: '/credentials'
      fullPath: '/settings/credentials'
      preLoaderRoute: typeof AuthenticatedSettingsCredentialsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/design': {
      id: '/_authenticated/settings/design'
      path: '/design'
      fullPath: '/settings/design'
      preLoaderRoute: typeof AuthenticatedSettingsDesignRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/director-report': {
      id: '/_authenticated/settings/director-report'
      path: '/director-report'
      fullPath: '/settings/director-report'
      preLoaderRoute: typeof AuthenticatedSettingsDirectorReportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/grade-template': {
      id: '/_authenticated/settings/grade-template'
      path: '/grade-template'
      fullPath: '/settings/grade-template'
      preLoaderRoute: typeof AuthenticatedSettingsGradeTemplateRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/homepage-courses': {
      id: '/_authenticated/settings/homepage-courses'
      path: '/homepage-courses'
      fullPath: '/settings/homepage-courses'
      preLoaderRoute: typeof AuthenticatedSettingsHomepageCoursesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/marketplace': {
      id: '/_authenticated/settings/marketplace'
      path: '/marketplace'
      fullPath: '/settings/marketplace'
      preLoaderRoute: typeof AuthenticatedSettingsMarketplaceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/news': {
      id: '/_authenticated/settings/news'
      path: '/news'
      fullPath: '/settings/news'
      preLoaderRoute: typeof AuthenticatedSettingsNewsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/reports': {
      id: '/_authenticated/settings/reports'
      path: '/reports'
      fullPath: '/settings/reports'
      preLoaderRoute: typeof AuthenticatedSettingsReportsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/stats': {
      id: '/_authenticated/settings/stats'
      path: '/stats'
      fullPath: '/settings/stats'
      preLoaderRoute: typeof AuthenticatedSettingsStatsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/subjects': {
      id: '/_authenticated/settings/subjects'
      path: '/subjects'
      fullPath: '/settings/subjects'
      preLoaderRoute: typeof AuthenticatedSettingsSubjectsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/teachers': {
      id: '/_authenticated/settings/teachers'
      path: '/teachers'
      fullPath: '/settings/teachers'
      preLoaderRoute: typeof AuthenticatedSettingsTeachersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/telephony': {
      id: '/_authenticated/settings/telephony'
      path: '/telephony'
      fullPath: '/settings/telephony'
      preLoaderRoute: typeof AuthenticatedSettingsTelephonyRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/api/public/cron/daily-report': {
      id: '/api/public/cron/daily-report'
      path: '/api/public/cron/daily-report'
      fullPath: '/api/public/cron/daily-report'
      preLoaderRoute: typeof ApiPublicCronDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notifications-dispatch': {
      id: '/api/public/cron/notifications-dispatch'
      path: '/api/public/cron/notifications-dispatch'
      fullPath: '/api/public/cron/notifications-dispatch'
      preLoaderRoute: typeof ApiPublicCronNotificationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/parent-digest': {
      id: '/api/public/cron/parent-digest'
      path: '/api/public/cron/parent-digest'
      fullPath: '/api/public/cron/parent-digest'
      preLoaderRoute: typeof ApiPublicCronParentDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/receipt-queue': {
      id: '/api/public/cron/receipt-queue'
      path: '/api/public/cron/receipt-queue'
      fullPath: '/api/public/cron/receipt-queue'
      preLoaderRoute: typeof ApiPublicCronReceiptQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reminders': {
      id: '/api/public/cron/reminders'
      path: '/api/public/cron/reminders'
      fullPath: '/api/public/cron/reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telephony/outbox': {
      id: '/api/public/telephony/outbox'
      path: '/api/public/telephony/outbox'
      fullPath: '/api/public/telephony/outbox'
      preLoaderRoute: typeof ApiPublicTelephonyOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telephony/sip-webhook': {
      id: '/api/public/telephony/sip-webhook'
      path: '/api/public/telephony/sip-webhook'
      fullPath: '/api/public/telephony/sip-webhook'
      preLoaderRoute: typeof ApiPublicTelephonySipWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telephony/webhook': {
      id: '/api/public/telephony/webhook'
      path: '/api/public/telephony/webhook'
      fullPath: '/api/public/telephony/webhook'
      preLoaderRoute: typeof ApiPublicTelephonyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsCashRegisterRoute: typeof AuthenticatedSettingsCashRegisterRoute
  AuthenticatedSettingsContactRoute: typeof AuthenticatedSettingsContactRoute
  AuthenticatedSettingsCredentialsRoute: typeof AuthenticatedSettingsCredentialsRoute
  AuthenticatedSettingsDesignRoute: typeof AuthenticatedSettingsDesignRoute
  AuthenticatedSettingsDirectorReportRoute: typeof AuthenticatedSettingsDirectorReportRoute
  AuthenticatedSettingsGradeTemplateRoute: typeof AuthenticatedSettingsGradeTemplateRoute
  AuthenticatedSettingsHomepageCoursesRoute: typeof AuthenticatedSettingsHomepageCoursesRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsMarketplaceRoute: typeof AuthenticatedSettingsMarketplaceRoute
  AuthenticatedSettingsNewsRoute: typeof AuthenticatedSettingsNewsRoute
  AuthenticatedSettingsReportsRoute: typeof AuthenticatedSettingsReportsRoute
  AuthenticatedSettingsStatsRoute: typeof AuthenticatedSettingsStatsRoute
  AuthenticatedSettingsSubjectsRoute: typeof AuthenticatedSettingsSubjectsRoute
  AuthenticatedSettingsTeachersRoute: typeof AuthenticatedSettingsTeachersRoute
  AuthenticatedSettingsTelephonyRoute: typeof AuthenticatedSettingsTelephonyRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsCashRegisterRoute:
    AuthenticatedSettingsCashRegisterRoute,
  AuthenticatedSettingsContactRoute: AuthenticatedSettingsContactRoute,
  AuthenticatedSettingsCredentialsRoute: AuthenticatedSettingsCredentialsRoute,
  AuthenticatedSettingsDesignRoute: AuthenticatedSettingsDesignRoute,
  AuthenticatedSettingsDirectorReportRoute:
    AuthenticatedSettingsDirectorReportRoute,
  AuthenticatedSettingsGradeTemplateRoute:
    AuthenticatedSettingsGradeTemplateRoute,
  AuthenticatedSettingsHomepageCoursesRoute:
    AuthenticatedSettingsHomepageCoursesRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsMarketplaceRoute: AuthenticatedSettingsMarketplaceRoute,
  AuthenticatedSettingsNewsRoute: AuthenticatedSettingsNewsRoute,
  AuthenticatedSettingsReportsRoute: AuthenticatedSettingsReportsRoute,
  AuthenticatedSettingsStatsRoute: AuthenticatedSettingsStatsRoute,
  AuthenticatedSettingsSubjectsRoute: AuthenticatedSettingsSubjectsRoute,
  AuthenticatedSettingsTeachersRoute: AuthenticatedSettingsTeachersRoute,
  AuthenticatedSettingsTelephonyRoute: AuthenticatedSettingsTelephonyRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBehaviorRoute: typeof AuthenticatedBehaviorRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaceIdRoute: typeof AuthenticatedFaceIdRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGradesRoute: typeof AuthenticatedGradesRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedTeacherBalanceRoute: typeof AuthenticatedTeacherBalanceRoute
  AuthenticatedTeacherPanelRoute: typeof AuthenticatedTeacherPanelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBehaviorRoute: AuthenticatedBehaviorRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaceIdRoute: AuthenticatedFaceIdRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGradesRoute: AuthenticatedGradesRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedTeacherBalanceRoute: AuthenticatedTeacherBalanceRoute,
  AuthenticatedTeacherPanelRoute: AuthenticatedTeacherPanelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BootstrapRoute: BootstrapRoute,
  ReceiptIdRoute: ReceiptIdRoute,
  ApiPublicCronDailyReportRoute: ApiPublicCronDailyReportRoute,
  ApiPublicCronNotificationsDispatchRoute:
    ApiPublicCronNotificationsDispatchRoute,
  ApiPublicCronParentDigestRoute: ApiPublicCronParentDigestRoute,
  ApiPublicCronReceiptQueueRoute: ApiPublicCronReceiptQueueRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicTelephonyOutboxRoute: ApiPublicTelephonyOutboxRoute,
  ApiPublicTelephonySipWebhookRoute: ApiPublicTelephonySipWebhookRoute,
  ApiPublicTelephonyWebhookRoute: ApiPublicTelephonyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
