/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as UniRouteImport } from './routes/uni'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedBehaviorRouteImport } from './routes/_authenticated/behavior'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedCashShiftsRouteImport } from './routes/_authenticated/cash-shifts'
import { Route as AuthenticatedCheckinLocationsRouteImport } from './routes/_authenticated/checkin-locations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDebtorsRouteImport } from './routes/_authenticated/debtors'
import { Route as AuthenticatedFaceIdRouteImport } from './routes/_authenticated/face-id'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedKnowledgeGameRouteImport } from './routes/_authenticated/knowledge-game'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMethodologyRouteImport } from './routes/_authenticated/methodology'
import { Route as AuthenticatedPaymentReceiptsRouteImport } from './routes/_authenticated/payment-receipts'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedTeacherBalanceRouteImport } from './routes/_authenticated/teacher-balance'
import { Route as AuthenticatedTeacherKpiRouteImport } from './routes/_authenticated/teacher-kpi'
import { Route as AuthenticatedTeacherPanelRouteImport } from './routes/_authenticated/teacher-panel'
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers'
import { Route as AuthenticatedVideoLessonsRouteImport } from './routes/_authenticated/video-lessons'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsContactRouteImport } from './routes/_authenticated/settings.contact'
import { Route as AuthenticatedSettingsCredentialsRouteImport } from './routes/_authenticated/settings.credentials'
import { Route as AuthenticatedSettingsDesignRouteImport } from './routes/_authenticated/settings.design'
import { Route as AuthenticatedSettingsDirectorReportRouteImport } from './routes/_authenticated/settings.director-report'
import { Route as AuthenticatedSettingsDonationRouteImport } from './routes/_authenticated/settings.donation'
import { Route as AuthenticatedSettingsHomepageCoursesRouteImport } from './routes/_authenticated/settings.homepage-courses'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsMarketplaceRouteImport } from './routes/_authenticated/settings.marketplace'
import { Route as AuthenticatedSettingsNewsRouteImport } from './routes/_authenticated/settings.news'
import { Route as AuthenticatedSettingsReportsRouteImport } from './routes/_authenticated/settings.reports'
import { Route as AuthenticatedSettingsSetupRouteImport } from './routes/_authenticated/settings.setup'
import { Route as AuthenticatedSettingsStatsRouteImport } from './routes/_authenticated/settings.stats'
import { Route as AuthenticatedSettingsSubjectsRouteImport } from './routes/_authenticated/settings.subjects'
import { Route as AuthenticatedSettingsSubscriptionRouteImport } from './routes/_authenticated/settings.subscription'
import { Route as AuthenticatedSettingsTeachersRouteImport } from './routes/_authenticated/settings.teachers'
import { Route as AuthenticatedSettingsTelephonyRouteImport } from './routes/_authenticated/settings.telephony'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as ApiPublicCronDailyReportRouteImport } from './routes/api/public/cron.daily-report'
import { Route as ApiPublicCronNotificationsDispatchRouteImport } from './routes/api/public/cron.notifications-dispatch'
import { Route as ApiPublicCronParentDigestRouteImport } from './routes/api/public/cron.parent-digest'
import { Route as ApiPublicCronReceiptQueueRouteImport } from './routes/api/public/cron.receipt-queue'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron.reminders'
import { Route as ApiPublicHealthConfigRouteImport } from './routes/api/public/health.config'
import { Route as ApiPublicHealthLiveRouteImport } from './routes/api/public/health.live'
import { Route as ApiPublicHealthReadyRouteImport } from './routes/api/public/health.ready'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram.webhook'
import { Route as ApiPublicTelephonyOutboxRouteImport } from './routes/api/public/telephony.outbox'
import { Route as ApiPublicTelephonySipWebhookRouteImport } from './routes/api/public/telephony.sip-webhook'
import { Route as ApiPublicTelephonyWebhookRouteImport } from './routes/api/public/telephony.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const UniRoute = UniRouteImport.update({
  id: '/uni',
  path: '/uni',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBehaviorRoute = AuthenticatedBehaviorRouteImport.update({
  id: '/behavior',
  path: '/behavior',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashShiftsRoute = AuthenticatedCashShiftsRouteImport.update({
  id: '/cash-shifts',
  path: '/cash-shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinLocationsRoute =
  AuthenticatedCheckinLocationsRouteImport.update({
    id: '/checkin-locations',
    path: '/checkin-locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebtorsRoute = AuthenticatedDebtorsRouteImport.update({
  id: '/debtors',
  path: '/debtors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaceIdRoute = AuthenticatedFaceIdRouteImport.update({
  id: '/face-id',
  path: '/face-id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeGameRoute =
  AuthenticatedKnowledgeGameRouteImport.update({
    id: '/knowledge-game',
    path: '/knowledge-game',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMethodologyRoute =
  AuthenticatedMethodologyRouteImport.update({
    id: '/methodology',
    path: '/methodology',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentReceiptsRoute =
  AuthenticatedPaymentReceiptsRouteImport.update({
    id: '/payment-receipts',
    path: '/payment-receipts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherBalanceRoute =
  AuthenticatedTeacherBalanceRouteImport.update({
    id: '/teacher-balance',
    path: '/teacher-balance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherKpiRoute = AuthenticatedTeacherKpiRouteImport.update({
  id: '/teacher-kpi',
  path: '/teacher-kpi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherPanelRoute =
  AuthenticatedTeacherPanelRouteImport.update({
    id: '/teacher-panel',
    path: '/teacher-panel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideoLessonsRoute =
  AuthenticatedVideoLessonsRouteImport.update({
    id: '/video-lessons',
    path: '/video-lessons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsContactRoute =
  AuthenticatedSettingsContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCredentialsRoute =
  AuthenticatedSettingsCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDesignRoute =
  AuthenticatedSettingsDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDirectorReportRoute =
  AuthenticatedSettingsDirectorReportRouteImport.update({
    id: '/director-report',
    path: '/director-report',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDonationRoute =
  AuthenticatedSettingsDonationRouteImport.update({
    id: '/donation',
    path: '/donation',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsHomepageCoursesRoute =
  AuthenticatedSettingsHomepageCoursesRouteImport.update({
    id: '/homepage-courses',
    path: '/homepage-courses',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMarketplaceRoute =
  AuthenticatedSettingsMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNewsRoute =
  AuthenticatedSettingsNewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsReportsRoute =
  AuthenticatedSettingsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSetupRoute =
  AuthenticatedSettingsSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsStatsRoute =
  AuthenticatedSettingsStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSubjectsRoute =
  AuthenticatedSettingsSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSubscriptionRoute =
  AuthenticatedSettingsSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeachersRoute =
  AuthenticatedSettingsTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTelephonyRoute =
  AuthenticatedSettingsTelephonyRouteImport.update({
    id: '/telephony',
    path: '/telephony',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)
const ApiPublicCronDailyReportRoute =
  ApiPublicCronDailyReportRouteImport.update({
    id: '/api/public/cron/daily-report',
    path: '/api/public/cron/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronNotificationsDispatchRoute =
  ApiPublicCronNotificationsDispatchRouteImport.update({
    id: '/api/public/cron/notifications-dispatch',
    path: '/api/public/cron/notifications-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronParentDigestRoute =
  ApiPublicCronParentDigestRouteImport.update({
    id: '/api/public/cron/parent-digest',
    path: '/api/public/cron/parent-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReceiptQueueRoute =
  ApiPublicCronReceiptQueueRouteImport.update({
    id: '/api/public/cron/receipt-queue',
    path: '/api/public/cron/receipt-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron/reminders',
  path: '/api/public/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthConfigRoute = ApiPublicHealthConfigRouteImport.update({
  id: '/api/public/health/config',
  path: '/api/public/health/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthLiveRoute = ApiPublicHealthLiveRouteImport.update({
  id: '/api/public/health/live',
  path: '/api/public/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthReadyRoute = ApiPublicHealthReadyRouteImport.update({
  id: '/api/public/health/ready',
  path: '/api/public/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelephonyOutboxRoute =
  ApiPublicTelephonyOutboxRouteImport.update({
    id: '/api/public/telephony/outbox',
    path: '/api/public/telephony/outbox',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelephonySipWebhookRoute =
  ApiPublicTelephonySipWebhookRouteImport.update({
    id: '/api/public/telephony/sip-webhook',
    path: '/api/public/telephony/sip-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelephonyWebhookRoute =
  ApiPublicTelephonyWebhookRouteImport.update({
    id: '/api/public/telephony/webhook',
    path: '/api/public/telephony/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/donate': typeof DonateRoute
  '/mcp': typeof McpRoute
  '/uni': typeof UniRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/behavior': typeof AuthenticatedBehaviorRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/cash-shifts': typeof AuthenticatedCashShiftsRoute
  '/checkin-locations': typeof AuthenticatedCheckinLocationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debtors': typeof AuthenticatedDebtorsRoute
  '/face-id': typeof AuthenticatedFaceIdRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/import': typeof AuthenticatedImportRoute
  '/knowledge-game': typeof AuthenticatedKnowledgeGameRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/methodology': typeof AuthenticatedMethodologyRoute
  '/payment-receipts': typeof AuthenticatedPaymentReceiptsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/teacher-balance': typeof AuthenticatedTeacherBalanceRoute
  '/teacher-kpi': typeof AuthenticatedTeacherKpiRoute
  '/teacher-panel': typeof AuthenticatedTeacherPanelRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/video-lessons': typeof AuthenticatedVideoLessonsRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/settings/contact': typeof AuthenticatedSettingsContactRoute
  '/settings/credentials': typeof AuthenticatedSettingsCredentialsRoute
  '/settings/design': typeof AuthenticatedSettingsDesignRoute
  '/settings/director-report': typeof AuthenticatedSettingsDirectorReportRoute
  '/settings/donation': typeof AuthenticatedSettingsDonationRoute
  '/settings/homepage-courses': typeof AuthenticatedSettingsHomepageCoursesRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/marketplace': typeof AuthenticatedSettingsMarketplaceRoute
  '/settings/news': typeof AuthenticatedSettingsNewsRoute
  '/settings/reports': typeof AuthenticatedSettingsReportsRoute
  '/settings/setup': typeof AuthenticatedSettingsSetupRoute
  '/settings/stats': typeof AuthenticatedSettingsStatsRoute
  '/settings/subjects': typeof AuthenticatedSettingsSubjectsRoute
  '/settings/subscription': typeof AuthenticatedSettingsSubscriptionRoute
  '/settings/teachers': typeof AuthenticatedSettingsTeachersRoute
  '/settings/telephony': typeof AuthenticatedSettingsTelephonyRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
  '/api/public/cron/notifications-dispatch': typeof ApiPublicCronNotificationsDispatchRoute
  '/api/public/cron/parent-digest': typeof ApiPublicCronParentDigestRoute
  '/api/public/cron/receipt-queue': typeof ApiPublicCronReceiptQueueRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/health/config': typeof ApiPublicHealthConfigRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telephony/outbox': typeof ApiPublicTelephonyOutboxRoute
  '/api/public/telephony/sip-webhook': typeof ApiPublicTelephonySipWebhookRoute
  '/api/public/telephony/webhook': typeof ApiPublicTelephonyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/donate': typeof DonateRoute
  '/mcp': typeof McpRoute
  '/uni': typeof UniRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/behavior': typeof AuthenticatedBehaviorRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/cash-shifts': typeof AuthenticatedCashShiftsRoute
  '/checkin-locations': typeof AuthenticatedCheckinLocationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debtors': typeof AuthenticatedDebtorsRoute
  '/face-id': typeof AuthenticatedFaceIdRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/import': typeof AuthenticatedImportRoute
  '/knowledge-game': typeof AuthenticatedKnowledgeGameRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/methodology': typeof AuthenticatedMethodologyRoute
  '/payment-receipts': typeof AuthenticatedPaymentReceiptsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/search': typeof AuthenticatedSearchRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/teacher-balance': typeof AuthenticatedTeacherBalanceRoute
  '/teacher-kpi': typeof AuthenticatedTeacherKpiRoute
  '/teacher-panel': typeof AuthenticatedTeacherPanelRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/video-lessons': typeof AuthenticatedVideoLessonsRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/settings/contact': typeof AuthenticatedSettingsContactRoute
  '/settings/credentials': typeof AuthenticatedSettingsCredentialsRoute
  '/settings/design': typeof AuthenticatedSettingsDesignRoute
  '/settings/director-report': typeof AuthenticatedSettingsDirectorReportRoute
  '/settings/donation': typeof AuthenticatedSettingsDonationRoute
  '/settings/homepage-courses': typeof AuthenticatedSettingsHomepageCoursesRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/marketplace': typeof AuthenticatedSettingsMarketplaceRoute
  '/settings/news': typeof AuthenticatedSettingsNewsRoute
  '/settings/reports': typeof AuthenticatedSettingsReportsRoute
  '/settings/setup': typeof AuthenticatedSettingsSetupRoute
  '/settings/stats': typeof AuthenticatedSettingsStatsRoute
  '/settings/subjects': typeof AuthenticatedSettingsSubjectsRoute
  '/settings/subscription': typeof AuthenticatedSettingsSubscriptionRoute
  '/settings/teachers': typeof AuthenticatedSettingsTeachersRoute
  '/settings/telephony': typeof AuthenticatedSettingsTelephonyRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
  '/api/public/cron/notifications-dispatch': typeof ApiPublicCronNotificationsDispatchRoute
  '/api/public/cron/parent-digest': typeof ApiPublicCronParentDigestRoute
  '/api/public/cron/receipt-queue': typeof ApiPublicCronReceiptQueueRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/health/config': typeof ApiPublicHealthConfigRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telephony/outbox': typeof ApiPublicTelephonyOutboxRoute
  '/api/public/telephony/sip-webhook': typeof ApiPublicTelephonySipWebhookRoute
  '/api/public/telephony/webhook': typeof ApiPublicTelephonyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/donate': typeof DonateRoute
  '/mcp': typeof McpRoute
  '/uni': typeof UniRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/behavior': typeof AuthenticatedBehaviorRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/cash-shifts': typeof AuthenticatedCashShiftsRoute
  '/_authenticated/checkin-locations': typeof AuthenticatedCheckinLocationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/debtors': typeof AuthenticatedDebtorsRoute
  '/_authenticated/face-id': typeof AuthenticatedFaceIdRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/guide': typeof AuthenticatedGuideRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/knowledge-game': typeof AuthenticatedKnowledgeGameRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/methodology': typeof AuthenticatedMethodologyRoute
  '/_authenticated/payment-receipts': typeof AuthenticatedPaymentReceiptsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/teacher-balance': typeof AuthenticatedTeacherBalanceRoute
  '/_authenticated/teacher-kpi': typeof AuthenticatedTeacherKpiRoute
  '/_authenticated/teacher-panel': typeof AuthenticatedTeacherPanelRoute
  '/_authenticated/teachers': typeof AuthenticatedTeachersRoute
  '/_authenticated/video-lessons': typeof AuthenticatedVideoLessonsRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/settings/contact': typeof AuthenticatedSettingsContactRoute
  '/_authenticated/settings/credentials': typeof AuthenticatedSettingsCredentialsRoute
  '/_authenticated/settings/design': typeof AuthenticatedSettingsDesignRoute
  '/_authenticated/settings/director-report': typeof AuthenticatedSettingsDirectorReportRoute
  '/_authenticated/settings/donation': typeof AuthenticatedSettingsDonationRoute
  '/_authenticated/settings/homepage-courses': typeof AuthenticatedSettingsHomepageCoursesRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/marketplace': typeof AuthenticatedSettingsMarketplaceRoute
  '/_authenticated/settings/news': typeof AuthenticatedSettingsNewsRoute
  '/_authenticated/settings/reports': typeof AuthenticatedSettingsReportsRoute
  '/_authenticated/settings/setup': typeof AuthenticatedSettingsSetupRoute
  '/_authenticated/settings/stats': typeof AuthenticatedSettingsStatsRoute
  '/_authenticated/settings/subjects': typeof AuthenticatedSettingsSubjectsRoute
  '/_authenticated/settings/subscription': typeof AuthenticatedSettingsSubscriptionRoute
  '/_authenticated/settings/teachers': typeof AuthenticatedSettingsTeachersRoute
  '/_authenticated/settings/telephony': typeof AuthenticatedSettingsTelephonyRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
  '/api/public/cron/notifications-dispatch': typeof ApiPublicCronNotificationsDispatchRoute
  '/api/public/cron/parent-digest': typeof ApiPublicCronParentDigestRoute
  '/api/public/cron/receipt-queue': typeof ApiPublicCronReceiptQueueRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/health/config': typeof ApiPublicHealthConfigRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/telephony/outbox': typeof ApiPublicTelephonyOutboxRoute
  '/api/public/telephony/sip-webhook': typeof ApiPublicTelephonySipWebhookRoute
  '/api/public/telephony/webhook': typeof ApiPublicTelephonyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bootstrap'
    | '/donate'
    | '/mcp'
    | '/uni'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/attendance'
    | '/behavior'
    | '/calls'
    | '/cash-shifts'
    | '/checkin-locations'
    | '/dashboard'
    | '/debtors'
    | '/face-id'
    | '/finance'
    | '/groups'
    | '/guide'
    | '/import'
    | '/knowledge-game'
    | '/leads'
    | '/marketplace'
    | '/messages'
    | '/methodology'
    | '/payment-receipts'
    | '/payments'
    | '/payroll'
    | '/platform'
    | '/reports'
    | '/roadmap'
    | '/rooms'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/students'
    | '/teacher-balance'
    | '/teacher-kpi'
    | '/teacher-panel'
    | '/teachers'
    | '/video-lessons'
    | '/receipt/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/settings/contact'
    | '/settings/credentials'
    | '/settings/design'
    | '/settings/director-report'
    | '/settings/donation'
    | '/settings/homepage-courses'
    | '/settings/integrations'
    | '/settings/marketplace'
    | '/settings/news'
    | '/settings/reports'
    | '/settings/setup'
    | '/settings/stats'
    | '/settings/subjects'
    | '/settings/subscription'
    | '/settings/teachers'
    | '/settings/telephony'
    | '/students/$id'
    | '/settings/'
    | '/api/public/cron/daily-report'
    | '/api/public/cron/notifications-dispatch'
    | '/api/public/cron/parent-digest'
    | '/api/public/cron/receipt-queue'
    | '/api/public/cron/reminders'
    | '/api/public/health/config'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/telegram/webhook'
    | '/api/public/telephony/outbox'
    | '/api/public/telephony/sip-webhook'
    | '/api/public/telephony/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bootstrap'
    | '/donate'
    | '/mcp'
    | '/uni'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/attendance'
    | '/behavior'
    | '/calls'
    | '/cash-shifts'
    | '/checkin-locations'
    | '/dashboard'
    | '/debtors'
    | '/face-id'
    | '/finance'
    | '/groups'
    | '/guide'
    | '/import'
    | '/knowledge-game'
    | '/leads'
    | '/marketplace'
    | '/messages'
    | '/methodology'
    | '/payment-receipts'
    | '/payments'
    | '/payroll'
    | '/platform'
    | '/reports'
    | '/roadmap'
    | '/rooms'
    | '/schedule'
    | '/search'
    | '/students'
    | '/teacher-balance'
    | '/teacher-kpi'
    | '/teacher-panel'
    | '/teachers'
    | '/video-lessons'
    | '/receipt/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/settings/contact'
    | '/settings/credentials'
    | '/settings/design'
    | '/settings/director-report'
    | '/settings/donation'
    | '/settings/homepage-courses'
    | '/settings/integrations'
    | '/settings/marketplace'
    | '/settings/news'
    | '/settings/reports'
    | '/settings/setup'
    | '/settings/stats'
    | '/settings/subjects'
    | '/settings/subscription'
    | '/settings/teachers'
    | '/settings/telephony'
    | '/students/$id'
    | '/settings'
    | '/api/public/cron/daily-report'
    | '/api/public/cron/notifications-dispatch'
    | '/api/public/cron/parent-digest'
    | '/api/public/cron/receipt-queue'
    | '/api/public/cron/reminders'
    | '/api/public/health/config'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/telegram/webhook'
    | '/api/public/telephony/outbox'
    | '/api/public/telephony/sip-webhook'
    | '/api/public/telephony/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bootstrap'
    | '/donate'
    | '/mcp'
    | '/uni'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/attendance'
    | '/_authenticated/behavior'
    | '/_authenticated/calls'
    | '/_authenticated/cash-shifts'
    | '/_authenticated/checkin-locations'
    | '/_authenticated/dashboard'
    | '/_authenticated/debtors'
    | '/_authenticated/face-id'
    | '/_authenticated/finance'
    | '/_authenticated/groups'
    | '/_authenticated/guide'
    | '/_authenticated/import'
    | '/_authenticated/knowledge-game'
    | '/_authenticated/leads'
    | '/_authenticated/marketplace'
    | '/_authenticated/messages'
    | '/_authenticated/methodology'
    | '/_authenticated/payment-receipts'
    | '/_authenticated/payments'
    | '/_authenticated/payroll'
    | '/_authenticated/platform'
    | '/_authenticated/reports'
    | '/_authenticated/roadmap'
    | '/_authenticated/rooms'
    | '/_authenticated/schedule'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/teacher-balance'
    | '/_authenticated/teacher-kpi'
    | '/_authenticated/teacher-panel'
    | '/_authenticated/teachers'
    | '/_authenticated/video-lessons'
    | '/receipt/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/settings/contact'
    | '/_authenticated/settings/credentials'
    | '/_authenticated/settings/design'
    | '/_authenticated/settings/director-report'
    | '/_authenticated/settings/donation'
    | '/_authenticated/settings/homepage-courses'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/marketplace'
    | '/_authenticated/settings/news'
    | '/_authenticated/settings/reports'
    | '/_authenticated/settings/setup'
    | '/_authenticated/settings/stats'
    | '/_authenticated/settings/subjects'
    | '/_authenticated/settings/subscription'
    | '/_authenticated/settings/teachers'
    | '/_authenticated/settings/telephony'
    | '/_authenticated/students/$id'
    | '/_authenticated/settings/'
    | '/api/public/cron/daily-report'
    | '/api/public/cron/notifications-dispatch'
    | '/api/public/cron/parent-digest'
    | '/api/public/cron/receipt-queue'
    | '/api/public/cron/reminders'
    | '/api/public/health/config'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/telegram/webhook'
    | '/api/public/telephony/outbox'
    | '/api/public/telephony/sip-webhook'
    | '/api/public/telephony/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BootstrapRoute: typeof BootstrapRoute
  DonateRoute: typeof DonateRoute
  McpRoute: typeof McpRoute
  UniRoute: typeof UniRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicCronDailyReportRoute: typeof ApiPublicCronDailyReportRoute
  ApiPublicCronNotificationsDispatchRoute: typeof ApiPublicCronNotificationsDispatchRoute
  ApiPublicCronParentDigestRoute: typeof ApiPublicCronParentDigestRoute
  ApiPublicCronReceiptQueueRoute: typeof ApiPublicCronReceiptQueueRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
  ApiPublicHealthConfigRoute: typeof ApiPublicHealthConfigRoute
  ApiPublicHealthLiveRoute: typeof ApiPublicHealthLiveRoute
  ApiPublicHealthReadyRoute: typeof ApiPublicHealthReadyRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicTelephonyOutboxRoute: typeof ApiPublicTelephonyOutboxRoute
  ApiPublicTelephonySipWebhookRoute: typeof ApiPublicTelephonySipWebhookRoute
  ApiPublicTelephonyWebhookRoute: typeof ApiPublicTelephonyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni': {
      id: '/uni'
      path: '/uni'
      fullPath: '/uni'
      preLoaderRoute: typeof UniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/behavior': {
      id: '/_authenticated/behavior'
      path: '/behavior'
      fullPath: '/behavior'
      preLoaderRoute: typeof AuthenticatedBehaviorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-shifts': {
      id: '/_authenticated/cash-shifts'
      path: '/cash-shifts'
      fullPath: '/cash-shifts'
      preLoaderRoute: typeof AuthenticatedCashShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin-locations': {
      id: '/_authenticated/checkin-locations'
      path: '/checkin-locations'
      fullPath: '/checkin-locations'
      preLoaderRoute: typeof AuthenticatedCheckinLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debtors': {
      id: '/_authenticated/debtors'
      path: '/debtors'
      fullPath: '/debtors'
      preLoaderRoute: typeof AuthenticatedDebtorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/face-id': {
      id: '/_authenticated/face-id'
      path: '/face-id'
      fullPath: '/face-id'
      preLoaderRoute: typeof AuthenticatedFaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-game': {
      id: '/_authenticated/knowledge-game'
      path: '/knowledge-game'
      fullPath: '/knowledge-game'
      preLoaderRoute: typeof AuthenticatedKnowledgeGameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/methodology': {
      id: '/_authenticated/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof AuthenticatedMethodologyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-receipts': {
      id: '/_authenticated/payment-receipts'
      path: '/payment-receipts'
      fullPath: '/payment-receipts'
      preLoaderRoute: typeof AuthenticatedPaymentReceiptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-balance': {
      id: '/_authenticated/teacher-balance'
      path: '/teacher-balance'
      fullPath: '/teacher-balance'
      preLoaderRoute: typeof AuthenticatedTeacherBalanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-kpi': {
      id: '/_authenticated/teacher-kpi'
      path: '/teacher-kpi'
      fullPath: '/teacher-kpi'
      preLoaderRoute: typeof AuthenticatedTeacherKpiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-panel': {
      id: '/_authenticated/teacher-panel'
      path: '/teacher-panel'
      fullPath: '/teacher-panel'
      preLoaderRoute: typeof AuthenticatedTeacherPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-lessons': {
      id: '/_authenticated/video-lessons'
      path: '/video-lessons'
      fullPath: '/video-lessons'
      preLoaderRoute: typeof AuthenticatedVideoLessonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/contact': {
      id: '/_authenticated/settings/contact'
      path: '/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof AuthenticatedSettingsContactRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/credentials': {
      id: '/_authenticated/settings/credentials'
      path: '/credentials'
      fullPath: '/settings/credentials'
      preLoaderRoute: typeof AuthenticatedSettingsCredentialsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/design': {
      id: '/_authenticated/settings/design'
      path: '/design'
      fullPath: '/settings/design'
      preLoaderRoute: typeof AuthenticatedSettingsDesignRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/director-report': {
      id: '/_authenticated/settings/director-report'
      path: '/director-report'
      fullPath: '/settings/director-report'
      preLoaderRoute: typeof AuthenticatedSettingsDirectorReportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/donation': {
      id: '/_authenticated/settings/donation'
      path: '/donation'
      fullPath: '/settings/donation'
      preLoaderRoute: typeof AuthenticatedSettingsDonationRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/homepage-courses': {
      id: '/_authenticated/settings/homepage-courses'
      path: '/homepage-courses'
      fullPath: '/settings/homepage-courses'
      preLoaderRoute: typeof AuthenticatedSettingsHomepageCoursesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/marketplace': {
      id: '/_authenticated/settings/marketplace'
      path: '/marketplace'
      fullPath: '/settings/marketplace'
      preLoaderRoute: typeof AuthenticatedSettingsMarketplaceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/news': {
      id: '/_authenticated/settings/news'
      path: '/news'
      fullPath: '/settings/news'
      preLoaderRoute: typeof AuthenticatedSettingsNewsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/reports': {
      id: '/_authenticated/settings/reports'
      path: '/reports'
      fullPath: '/settings/reports'
      preLoaderRoute: typeof AuthenticatedSettingsReportsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/setup': {
      id: '/_authenticated/settings/setup'
      path: '/setup'
      fullPath: '/settings/setup'
      preLoaderRoute: typeof AuthenticatedSettingsSetupRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/stats': {
      id: '/_authenticated/settings/stats'
      path: '/stats'
      fullPath: '/settings/stats'
      preLoaderRoute: typeof AuthenticatedSettingsStatsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/subjects': {
      id: '/_authenticated/settings/subjects'
      path: '/subjects'
      fullPath: '/settings/subjects'
      preLoaderRoute: typeof AuthenticatedSettingsSubjectsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/subscription': {
      id: '/_authenticated/settings/subscription'
      path: '/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof AuthenticatedSettingsSubscriptionRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/teachers': {
      id: '/_authenticated/settings/teachers'
      path: '/teachers'
      fullPath: '/settings/teachers'
      preLoaderRoute: typeof AuthenticatedSettingsTeachersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/telephony': {
      id: '/_authenticated/settings/telephony'
      path: '/telephony'
      fullPath: '/settings/telephony'
      preLoaderRoute: typeof AuthenticatedSettingsTelephonyRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/api/public/cron/daily-report': {
      id: '/api/public/cron/daily-report'
      path: '/api/public/cron/daily-report'
      fullPath: '/api/public/cron/daily-report'
      preLoaderRoute: typeof ApiPublicCronDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notifications-dispatch': {
      id: '/api/public/cron/notifications-dispatch'
      path: '/api/public/cron/notifications-dispatch'
      fullPath: '/api/public/cron/notifications-dispatch'
      preLoaderRoute: typeof ApiPublicCronNotificationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/parent-digest': {
      id: '/api/public/cron/parent-digest'
      path: '/api/public/cron/parent-digest'
      fullPath: '/api/public/cron/parent-digest'
      preLoaderRoute: typeof ApiPublicCronParentDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/receipt-queue': {
      id: '/api/public/cron/receipt-queue'
      path: '/api/public/cron/receipt-queue'
      fullPath: '/api/public/cron/receipt-queue'
      preLoaderRoute: typeof ApiPublicCronReceiptQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reminders': {
      id: '/api/public/cron/reminders'
      path: '/api/public/cron/reminders'
      fullPath: '/api/public/cron/reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/config': {
      id: '/api/public/health/config'
      path: '/api/public/health/config'
      fullPath: '/api/public/health/config'
      preLoaderRoute: typeof ApiPublicHealthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/live': {
      id: '/api/public/health/live'
      path: '/api/public/health/live'
      fullPath: '/api/public/health/live'
      preLoaderRoute: typeof ApiPublicHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/ready': {
      id: '/api/public/health/ready'
      path: '/api/public/health/ready'
      fullPath: '/api/public/health/ready'
      preLoaderRoute: typeof ApiPublicHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telephony/outbox': {
      id: '/api/public/telephony/outbox'
      path: '/api/public/telephony/outbox'
      fullPath: '/api/public/telephony/outbox'
      preLoaderRoute: typeof ApiPublicTelephonyOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telephony/sip-webhook': {
      id: '/api/public/telephony/sip-webhook'
      path: '/api/public/telephony/sip-webhook'
      fullPath: '/api/public/telephony/sip-webhook'
      preLoaderRoute: typeof ApiPublicTelephonySipWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telephony/webhook': {
      id: '/api/public/telephony/webhook'
      path: '/api/public/telephony/webhook'
      fullPath: '/api/public/telephony/webhook'
      preLoaderRoute: typeof ApiPublicTelephonyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsContactRoute: typeof AuthenticatedSettingsContactRoute
  AuthenticatedSettingsCredentialsRoute: typeof AuthenticatedSettingsCredentialsRoute
  AuthenticatedSettingsDesignRoute: typeof AuthenticatedSettingsDesignRoute
  AuthenticatedSettingsDirectorReportRoute: typeof AuthenticatedSettingsDirectorReportRoute
  AuthenticatedSettingsDonationRoute: typeof AuthenticatedSettingsDonationRoute
  AuthenticatedSettingsHomepageCoursesRoute: typeof AuthenticatedSettingsHomepageCoursesRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsMarketplaceRoute: typeof AuthenticatedSettingsMarketplaceRoute
  AuthenticatedSettingsNewsRoute: typeof AuthenticatedSettingsNewsRoute
  AuthenticatedSettingsReportsRoute: typeof AuthenticatedSettingsReportsRoute
  AuthenticatedSettingsSetupRoute: typeof AuthenticatedSettingsSetupRoute
  AuthenticatedSettingsStatsRoute: typeof AuthenticatedSettingsStatsRoute
  AuthenticatedSettingsSubjectsRoute: typeof AuthenticatedSettingsSubjectsRoute
  AuthenticatedSettingsSubscriptionRoute: typeof AuthenticatedSettingsSubscriptionRoute
  AuthenticatedSettingsTeachersRoute: typeof AuthenticatedSettingsTeachersRoute
  AuthenticatedSettingsTelephonyRoute: typeof AuthenticatedSettingsTelephonyRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsContactRoute: AuthenticatedSettingsContactRoute,
  AuthenticatedSettingsCredentialsRoute: AuthenticatedSettingsCredentialsRoute,
  AuthenticatedSettingsDesignRoute: AuthenticatedSettingsDesignRoute,
  AuthenticatedSettingsDirectorReportRoute:
    AuthenticatedSettingsDirectorReportRoute,
  AuthenticatedSettingsDonationRoute: AuthenticatedSettingsDonationRoute,
  AuthenticatedSettingsHomepageCoursesRoute:
    AuthenticatedSettingsHomepageCoursesRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsMarketplaceRoute: AuthenticatedSettingsMarketplaceRoute,
  AuthenticatedSettingsNewsRoute: AuthenticatedSettingsNewsRoute,
  AuthenticatedSettingsReportsRoute: AuthenticatedSettingsReportsRoute,
  AuthenticatedSettingsSetupRoute: AuthenticatedSettingsSetupRoute,
  AuthenticatedSettingsStatsRoute: AuthenticatedSettingsStatsRoute,
  AuthenticatedSettingsSubjectsRoute: AuthenticatedSettingsSubjectsRoute,
  AuthenticatedSettingsSubscriptionRoute:
    AuthenticatedSettingsSubscriptionRoute,
  AuthenticatedSettingsTeachersRoute: AuthenticatedSettingsTeachersRoute,
  AuthenticatedSettingsTelephonyRoute: AuthenticatedSettingsTelephonyRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBehaviorRoute: typeof AuthenticatedBehaviorRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedCashShiftsRoute: typeof AuthenticatedCashShiftsRoute
  AuthenticatedCheckinLocationsRoute: typeof AuthenticatedCheckinLocationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDebtorsRoute: typeof AuthenticatedDebtorsRoute
  AuthenticatedFaceIdRoute: typeof AuthenticatedFaceIdRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedKnowledgeGameRoute: typeof AuthenticatedKnowledgeGameRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMethodologyRoute: typeof AuthenticatedMethodologyRoute
  AuthenticatedPaymentReceiptsRoute: typeof AuthenticatedPaymentReceiptsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedTeacherBalanceRoute: typeof AuthenticatedTeacherBalanceRoute
  AuthenticatedTeacherKpiRoute: typeof AuthenticatedTeacherKpiRoute
  AuthenticatedTeacherPanelRoute: typeof AuthenticatedTeacherPanelRoute
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRoute
  AuthenticatedVideoLessonsRoute: typeof AuthenticatedVideoLessonsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBehaviorRoute: AuthenticatedBehaviorRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedCashShiftsRoute: AuthenticatedCashShiftsRoute,
  AuthenticatedCheckinLocationsRoute: AuthenticatedCheckinLocationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDebtorsRoute: AuthenticatedDebtorsRoute,
  AuthenticatedFaceIdRoute: AuthenticatedFaceIdRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedGuideRoute: AuthenticatedGuideRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedKnowledgeGameRoute: AuthenticatedKnowledgeGameRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMethodologyRoute: AuthenticatedMethodologyRoute,
  AuthenticatedPaymentReceiptsRoute: AuthenticatedPaymentReceiptsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedTeacherBalanceRoute: AuthenticatedTeacherBalanceRoute,
  AuthenticatedTeacherKpiRoute: AuthenticatedTeacherKpiRoute,
  AuthenticatedTeacherPanelRoute: AuthenticatedTeacherPanelRoute,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRoute,
  AuthenticatedVideoLessonsRoute: AuthenticatedVideoLessonsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BootstrapRoute: BootstrapRoute,
  DonateRoute: DonateRoute,
  McpRoute: McpRoute,
  UniRoute: UniRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ReceiptIdRoute: ReceiptIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicCronDailyReportRoute: ApiPublicCronDailyReportRoute,
  ApiPublicCronNotificationsDispatchRoute:
    ApiPublicCronNotificationsDispatchRoute,
  ApiPublicCronParentDigestRoute: ApiPublicCronParentDigestRoute,
  ApiPublicCronReceiptQueueRoute: ApiPublicCronReceiptQueueRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
  ApiPublicHealthConfigRoute: ApiPublicHealthConfigRoute,
  ApiPublicHealthLiveRoute: ApiPublicHealthLiveRoute,
  ApiPublicHealthReadyRoute: ApiPublicHealthReadyRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicTelephonyOutboxRoute: ApiPublicTelephonyOutboxRoute,
  ApiPublicTelephonySipWebhookRoute: ApiPublicTelephonySipWebhookRoute,
  ApiPublicTelephonyWebhookRoute: ApiPublicTelephonyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
